# Generated by Django 4.2 on 2025-06-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='last_seen',
            field=models.DateTimeField(),
        ),
    ]
