# Generated by Django 4.2 on 2025-07-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_attendancerecord_mac_address_attendancerecord_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='Unknown', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='Unknown', max_length=128),
            preserve_default=False,
        ),
    ]
